# Generated by Django 4.2.19 on 2025-02-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fielddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fielddata',
            old_name='field',
            new_name='main_field',
        ),
    ]
