# Generated by Django 4.2.19 on 2025-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_field_fielddata_main_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fielddata',
            name='is_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fielddata',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
