# Generated by Django 4.2.19 on 2025-02-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fielddata_crop_name_fielddata_is_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='is_not_crop',
            field=models.BooleanField(default=False),
        ),
    ]
