# Generated by Django 4.2.19 on 2025-04-09 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fielddata_is_not_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
